#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use IServ::DB;

my (@ips) = IServ::DB::SelectCol "SELECT IP FROM file_distribution;";

# disable file distribution for hosts where it is still enabled
if (@ips > 0) {
  system "/usr/lib/iserv/file_distribution_rpc", "root", "fdoff", @ips;
}

chdir "/var/lib/iserv/config/file-distribution" or die $!;
my @del = glob "*";

foreach my $del (@del) {
  # ignore iservchk stub file
  unless ($del eq "0.0.0.0") {
    unlink $del;
  }
}
