#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use IServ::DB;

my (@IPs) = IServ::DB::SelectCol "SELECT IP FROM file_distribution;";

# disable file distribution for hosts where it is still enabled
foreach my $IP (@IPs) {
  print "Disabled forgotten file distribution for $IP.\n";
  IServ::DB::Do "DELETE FROM file_distribution WHERE IP = ?", $IP;
}

chdir "/var/lib/iserv/config/file-distribution" or die $!;
my @del = glob "*";

foreach my $del (@del) {
  # ignore iservchk stub file
  unless ($del eq "0.0.0.0") {
    unlink $del;
  }
}
