#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use IServ::DB;

my (@ips) = IServ::DB::SelectCol "SELECT IP FROM computer_sound_lock;";

# disable file distribution for hosts where it is still enabled
if (@ips > 0) {
  print "disable sound lock on: @ips\n";
  system "/usr/lib/iserv/file_distribution_rpc", "root", "soundon", @ips;
}

