services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\FileDistributionBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources,Tests}'

    Stsbl\FileDistributionBundle\Entity\ExamRepository: ~

    Stsbl\FileDistributionBundle\Crud\ObjectManager\FileDistributionObjectManager:
        bind:
            $inner: '@IServ\CrudBundle\Doctrine\ORM\ORMObjectManager'
